---
name: Lint
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck lint
        run: shellcheck *.bash src/*.bash && echo "Shellcheck passed"
